/** Country names for registration location (separate from phone country code). */

export const COUNTRY_OPTIONS = [
  'India',
  'United Arab Emirates',
  'United States',
  'United Kingdom',
  'Singapore',
  'Australia',
  'Canada',
  'Nepal',
  'Bangladesh',
  'Pakistan',
  'Sri Lanka',
  'Germany',
  'France',
  'Netherlands',
  'Spain',
  'Italy',
  'Japan',
  'South Korea',
  'China',
  'Hong Kong',
  'Malaysia',
  'Indonesia',
  'Thailand',
  'Philippines',
  'Vietnam',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Oman',
  'Bahrain',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Brazil',
  'Mexico',
  'New Zealand',
  'Ireland',
  'Switzerland',
  'Sweden',
  'Norway',
  'Denmark',
  'Other',
] as const;

export type CountryOption = (typeof COUNTRY_OPTIONS)[number];
