/** Country names for registration location (separate from phone country code). */

export const COUNTRY_OPTIONS = [
  'India',
  'United Arab Emirates',
  'United States',
  'United Kingdom',
  'Singapore',
  'Australia',
  'Canada',
  'Nepal',
  'Bangladesh',
  'Pakistan',
  'Sri Lanka',
  'Germany',
  'France',
  'Netherlands',
  'Spain',
  'Italy',
  'Japan',
  'South Korea',
  'China',
  'Hong Kong',
  'Malaysia',
  'Indonesia',
  'Thailand',
  'Philippines',
  'Vietnam',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Oman',
  'Bahrain',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Brazil',
  'Mexico',
  'New Zealand',
  'Ireland',
  'Switzerland',
  'Sweden',
  'Norway',
  'Denmark',
  'Other',
] as const;

export type CountryOption = (typeof COUNTRY_OPTIONS)[number];

const COUNTRY_ISO: Record<string, string> = {
  India: 'IN',
  'United Arab Emirates': 'AE',
  'United States': 'US',
  'United Kingdom': 'GB',
  Singapore: 'SG',
  Australia: 'AU',
  Canada: 'CA',
  Nepal: 'NP',
  Bangladesh: 'BD',
  Pakistan: 'PK',
  'Sri Lanka': 'LK',
  Germany: 'DE',
  France: 'FR',
  Netherlands: 'NL',
  Spain: 'ES',
  Italy: 'IT',
  Japan: 'JP',
  'South Korea': 'KR',
  China: 'CN',
  'Hong Kong': 'HK',
  Malaysia: 'MY',
  Indonesia: 'ID',
  Thailand: 'TH',
  Philippines: 'PH',
  Vietnam: 'VN',
  'Saudi Arabia': 'SA',
  Qatar: 'QA',
  Kuwait: 'KW',
  Oman: 'OM',
  Bahrain: 'BH',
  'South Africa': 'ZA',
  Nigeria: 'NG',
  Kenya: 'KE',
  Brazil: 'BR',
  Mexico: 'MX',
  'New Zealand': 'NZ',
  Ireland: 'IE',
  Switzerland: 'CH',
  Sweden: 'SE',
  Norway: 'NO',
  Denmark: 'DK',
};

function isoToFlag(iso: string): string {
  return iso
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}

export function flagForCountry(country: string): string | undefined {
  const iso = COUNTRY_ISO[country];
  return iso ? isoToFlag(iso) : undefined;
}

/** Default IANA timezone when user picks a country (best-effort). */
export const COUNTRY_TIMEZONE: Record<string, string> = {
  India: 'Asia/Kolkata',
  'United Arab Emirates': 'Asia/Dubai',
  Oman: 'Asia/Muscat',
  Bahrain: 'Asia/Dubai',
  Qatar: 'Asia/Qatar',
  Kuwait: 'Asia/Kuwait',
  'Saudi Arabia': 'Asia/Riyadh',
  'United States': 'America/New_York',
  'United Kingdom': 'Europe/London',
  Singapore: 'Asia/Singapore',
  Australia: 'Australia/Sydney',
  Canada: 'America/Toronto',
  Nepal: 'Asia/Kathmandu',
  Bangladesh: 'Asia/Dhaka',
  Pakistan: 'Asia/Karachi',
  'Sri Lanka': 'Asia/Colombo',
  Germany: 'Europe/Berlin',
  France: 'Europe/Paris',
  Netherlands: 'Europe/Amsterdam',
  Spain: 'Europe/Madrid',
  Italy: 'Europe/Rome',
  Japan: 'Asia/Tokyo',
  'South Korea': 'Asia/Seoul',
  China: 'Asia/Shanghai',
  'Hong Kong': 'Asia/Hong_Kong',
  Malaysia: 'Asia/Kuala_Lumpur',
  Indonesia: 'Asia/Jakarta',
  Thailand: 'Asia/Bangkok',
  Philippines: 'Asia/Manila',
  Vietnam: 'Asia/Ho_Chi_Minh',
  'South Africa': 'Africa/Johannesburg',
  Nigeria: 'Africa/Lagos',
  Kenya: 'Africa/Nairobi',
  Brazil: 'America/Sao_Paulo',
  Mexico: 'America/Mexico_City',
  'New Zealand': 'Pacific/Auckland',
  Ireland: 'Europe/Dublin',
  Switzerland: 'Europe/Zurich',
  Sweden: 'Europe/Stockholm',
  Norway: 'Europe/Oslo',
  Denmark: 'Europe/Copenhagen',
  Other: 'UTC',
};

export function timezoneForCountry(country: string): string | null {
  return COUNTRY_TIMEZONE[country] || null;
}
